name: nivel_de_agua
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependências do projeto antigo
  flutter_bluetooth_serial: ^0.4.0 
  permission_handler: ^11.0.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1

  # Ícones padrão iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # Assets (caminho corrigido para funcionar no Linux/macOS também)
  assets:
    - assets/profile.jpg
    - assets/logo.png
    - assets/animations/loadinganimation.json
